### ISSUE TITLE
Return E(B-V) for arbitrary sample of (l, b, distance)

### ISSUE THREAD

**Issue by willclarkson** [willclarkson/rubinCadenceScratchWIC#21]
It would be good to include a method that returns E(B-V) for user-supplied l, b, distance arrays. Ideally this would be done without constructing the entire skymap separately for each distance. It's not clear to me if this is a simple extension of what we currently do for a single scalar distance, or instead is very difficult (to run quickly, anyway... a loop over the distances followed by application of the methods we already have, would be robust but might be slow for large numbers of objects. Worth exploring!).

**Comment by willclarkson** [comment]
Thinking about this a bit more... **[hp.get_interp_weights()](https://healpy.readthedocs.io/en/latest/generated/healpy.pixelfunc.get_interp_weights.html)** may be what we need... it returns the weighting coefficients in the healpix map that one would sum (multiplied by the actual array of values) to do the interpolation). This may be the way to get the best of both worlds: **get_interp_weights()** would tell the calling routine which of the healpix to sum to get the interpolated value, and then the choice of array would be the plane in the (ebv vs distance) array appropriate for each object.

**Comment by Thalos12** [comment]
Closing since this is added in the pull request #25.

**Comment by Thalos12** [comment]
I think this can be closed since this is added in the pull request #25.

**Comment by willclarkson** [comment]
OK closing this issue
