### ISSUE TITLE
impose maximum distance on L+19 (compareExtinctions.py)

### ISSUE THREAD

**Issue by willclarkson** [willclarkson/rubinCadenceScratchWIC#7]
Add a keyword to compareExtinctions.py to implement an alternative maximum distance for L+19 ("dmax_L19", say). Suggested behavior:

- If very large (1e6, say) then use L+19 all the way out to its maximum distance of validity
- If <=0, use L+19 only where Bovy et al. predicts zero extinction (i.e. scale L+19 to Planck in those sight lines)
- Otherwise use dmax_L19 as the maximum distance if this value is within the region at which L+19 is defined.

This should then give the user the option to use L+19 only over some limited distance range, or not use it at all, or revert to previous behavior.

**Comment by Thalos12** [comment]
I would propose something slightly different:

-  `dmax_L19=None` to signal that L+19 has to be used up to its maximum distance;
- `dmax_L19>0` to set the maximum distance, reduced to the maximum distance along the line of sight if larger);
- `dmax_L19=-1` to use L+19 only where Bovy preidicts zero;
- `dmax_L19=0` to disable L+19 if the user requires it.

Do you think it could work?

(Edited to remove the `=` from the second case)

**Comment by willclarkson** [comment]
I think this would work better! As long as it’s clearly documented in the docstring, whichever way works best is OK with me!

**Comment by Thalos12** [comment]
Great, thank you!

**Comment by willclarkson** [comment]
Thinking about it a bit more, there might be an issue distinguishing 0 from None, I think how we specify using L19 all the way out to the max distance depends on how the decision is made in the code. For example, I think that 

`dmax = np.min([myDist, maxL19])`

where one of those two variables on the right is the user supplied maximum, the other is the max distance at which L19 is defined, would implement the first, second and third bullet point in one line if a large distance is used instead of None for the first bullet.

**Comment by Thalos12** [comment]
Yes, that is a good point, and its simpler than what I had in mind. I will do as you suggested!

**Comment by willclarkson** [comment]
Correction: the line above would mean 0 would cause L19 to be ignored everywhere, I guess -1 could then trigger the use of L19 only where bovy predicts zero reddening. I guess there are a few ways to do this!

**Comment by Thalos12** [comment]
Some updates, I have added the limit as you suggested, so now a user can change the maximum distance for the L+19 profile.
I am still working on implementing the `-1` option however.

**Comment by Thalos12** [comment]
Also, in case of `dmaxL19=-1` and non-zero Bovy, as Lallement is not used there will be no correction of the profile where `ebvHybrid < minEBV`, is this ok?

**Comment by Thalos12** [comment]
Lastly, it seems `dmaxL19` is working where Bovy exists, but I currently do not know a pointing for which Bovy is null to test the opposite case, do you perhaps have one?

**Comment by willclarkson** [comment]
Hi @Thalos12 - great to see this progress! Just to be clear, I'm assuming dmaxL19 means L+19 is used where Bovy predicts zero, and dmaxL19 == 0 means L+19 is ignored even if Bovy is zero. If that's not what you have, you can probably translate the following suggestions into the implementation you do have:

- For the -1 option (i.e. L+19 only used where Bovy shows zero), I believe ~that's~ that swapping in L+19 for the fields where Bovy predicts zero is the default behavior. I think the way I'd handle this would be to modify the conditional on line 728 of the [current main version here](https://github.com/willclarkson/rubinCadenceScratchWIC/blob/main/python/compareExtinctions.py), so that it reads `if planck2DMed > 0. and dmaxL19 != 0:`  .  I *think* that would then cause the L19 to be ignored entirely if dmaxL19 ==0 or if the planck prediction is not available. For all other values of dmaxL19, L+19 would be swapped in where Bovy predicts zero.

- If L+19 is not to be used at all, even where Bovy predicts E(B-V) < minEBV, I think that's fine - as long as it's clear in the docstring and that the user knows that this is what they are getting. We might imagine throwing a warning in that instance. We're giving the user a range of options, and I think it's reasonable to give the user the option to strictly ignore L+19 if they wish.

- You asked for a field where Bovy predicts zero E(B-V). Try (l,b) = (-90, 65). The current behavior for that field is shown in [this plot](https://github.com/willclarkson/rubinCadenceScratchWIC/blob/main/python/plots/test_l270_b65_nside64_sub.png).

**Comment by Thalos12** [comment]
Thanks for these suggestions, I implemented them and below you can see two cases, both with `dmaxL19=-1`, the first with Bovy non zero and therefore no Lallement, the second with only Lallement, from the coordinates you wrote in the previous comment.

![onlyBovy](https://user-images.githubusercontent.com/13919407/113936820-a2909500-97f8-11eb-8b9c-3b18577a48c4.png)

![zeroBovy](https://user-images.githubusercontent.com/13919407/113936837-aae8d000-97f8-11eb-90bc-69f3f99ff291.png)

**Comment by willclarkson** [comment]
Very nice!!

I have made some updates to **readExtinction.py** to start the refactoring of a few methods into the ebv3d object, including the nice method you wrote to handle the colorbar labeling. I should be able to resume that in a couple of hours. This shouldn't cause any clashes with a pull request you may make.

**Comment by willclarkson** [comment]
What happens when you send in dmaxL19 = 0?

**Comment by Thalos12** [comment]
> What happens when you send in dmaxL19 = 0?

Sorry, I noticed your reply only now! Using dmaxL19=0 will disable Lallement and, if Bovy is not available, an E(B_V) profile with zeros everywhere is returned. A warning is issued so that the user can be aware of what happened.
